runtime: python27
api_version: 1
threadsafe: true

service: default

automatic_scaling:
    target_cpu_utilization: 0.65
    min_instances: 1
    max_instances: 2
    min_pending_latency: 30ms
    max_pending_latency: automatic

handlers:
    - url: /
      static_files: www/index.html
      upload: www/index.html

    - url: /(.*)
      static_files: www/\1
      upload: www/(.*)
